# Version: 1.0

From ubuntu:20.04
USER root


# Owner: Bahaeddine FERIANI


# Install OpenJDK-8

RUN apt-get update && \
    apt-get install -y openjdk-8-jdk && \
    apt-get install -y ant && \
    apt-get clean;
    
# Fix certificate issues

RUN apt-get update && \
    apt-get install ca-certificates-java && \
    apt-get clean && \
    update-ca-certificates -f;

# Setup JAVA_HOME 

ENV JAVA_HOME /usr/lib/jvm/java-8-openjdk-amd64/
RUN export JAVA_HOME

# Other dependencies and tools

RUN apt -y update && \
    apt -y upgrade && \
    apt install -y python3.8 && \
    apt install -y python3-pip && \
    apt install -y build-essential && \
    apt install -y libssl-dev && \
    apt install -y libffi-dev && \
    apt install -y python3-dev && \
    apt install -y netcat

# Jupyter lab & flask

RUN pip3 install jupyterlab && \
    pip3 install pyspark==3.3.2 &&\
    pip3 install flask
    
# Jupyter startup script

COPY start-jupyter.sh /
RUN chmod 777 /start-jupyter.sh

# Jupyter start with the container 

CMD ["bin/bash","/start-jupyter.sh"]
