version: "1.0"

#############################
# Owner: Bahaeddine FERIANI #
#############################

services:
  namenode:
    image: hadoopnamenode
    container_name: namenode
    restart: on-failure
    ports:
      - 9870:9870
      - 9000:9000
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=hadoop
    env_file:
      - ./hadoop.env
    networks:
      - kepler

  datanode:
    image: hadoopdatanode
    container_name: datanode
    restart: on-failure
    volumes:
      - hadoop_datanode:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    env_file:
      - ./hadoop.env
    networks:
      - kepler

  resourcemanager:
    image: hadooprecourcemanager
    container_name: resourcemanager
    restart: on-failure
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode:9864"
    env_file:
      - ./hadoop.env
    networks:
      - kepler

  nodemanager1:
    image: hadoopnodemanager
    container_name: nodemanager
    restart: on-failure
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode:9864 resourcemanager:8088"
    env_file:
      - ./hadoop.env
    networks:
      - kepler

volumes:
  hadoop_namenode:
  hadoop_datanode:
networks:
  kepler:
    name: kepler
    driver: bridge
