version: "1.0"

#############################
# Owner: Bahaeddine FERIANI #
#############################

services:
  pyspark:
    container_name: flaskapp
    image: flaskapp
    restart: on-failure
    ports:
      - "5000:5000"
    volumes:
      - ./data:/data
    networks:
      - kepler
networks:
  kepler:
    name: kepler
    driver: bridge
